dbt_nhl:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      host: trino
      port: 8080
      user: admin
      database: iceberg    # nome do catálogo no Trino
      schema: main
      threads: 4
